/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class DistortionAudioProcessorEditor  : public AudioProcessorEditor,public SliderListener,public ComboBoxListener, public Timer

{
public:
    DistortionAudioProcessorEditor (DistortionAudioProcessor& p);
    ~DistortionAudioProcessorEditor();

    //==============================================================================
    void timerCallback() override;
    void paint (Graphics&) override;
    void resized() override;
    void sliderValueChanged (Slider*) override;
    void comboBoxChanged (ComboBox*) ;
    
    
private:
    
    Label gainLabel_;
    Slider gainSlider_;
    ComboBox typeComboBox_;
    ScopedPointer<ResizableCornerComponent> resizer_;
    ComponentBoundsConstrainer resizeLimits_;
    
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    DistortionAudioProcessor& getProcessor() const
    {
        return static_cast <DistortionAudioProcessor&>(processor);
    }
    

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (DistortionAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
